package com.logify.actions

import com.intellij.lang.java.JavaLanguage
import com.intellij.openapi.actionSystem.ActionUpdateThread
import com.intellij.openapi.actionSystem.AnAction
import com.intellij.openapi.actionSystem.AnActionEvent
import com.intellij.openapi.actionSystem.CommonDataKeys
import com.intellij.openapi.command.WriteCommandAction
import com.intellij.openapi.fileEditor.FileEditorManager
import com.intellij.psi.PsiFile
import com.intellij.psi.PsiFileFactory
import com.intellij.psi.PsiJavaFile

/**
 * Right-click action (Java files): creates an "L.java" utility class in the same
 * directory as the current file.  If L.java already exists it is opened instead.
 */
class JavaWrapperGeneratorAction : AnAction("Insert Java Log Wrapper (L.java)") {

    override fun getActionUpdateThread() = ActionUpdateThread.BGT

    override fun update(e: AnActionEvent) {
        e.presentation.isEnabledAndVisible =
            e.getData(CommonDataKeys.PSI_FILE)?.name?.endsWith(".java") == true
    }

    override fun actionPerformed(e: AnActionEvent) {
        val project  = e.project ?: return
        val javaFile = e.getData(CommonDataKeys.PSI_FILE) as? PsiJavaFile ?: return
        val dir      = javaFile.containingDirectory ?: return

        WriteCommandAction.runWriteCommandAction(project, "Create L.java Log Wrapper", null, {
            try {
                val existing = dir.findFile("L.java")
                if (existing != null) {
                    FileEditorManager.getInstance(project).openFile(existing.virtualFile, true)
                    return@runWriteCommandAction
                }

                val content = buildContent(javaFile.packageName)
                val newFile = PsiFileFactory.getInstance(project)
                    .createFileFromText("L.java", JavaLanguage.INSTANCE, content) as PsiFile

                val added = dir.add(newFile) as PsiFile
                FileEditorManager.getInstance(project).openFile(added.virtualFile, true)
            } catch (ex: Exception) {
                // Never crash the IDE
            }
        })
    }

    private fun buildContent(pkg: String): String {
        val pkgLine = if (pkg.isNotEmpty()) "package $pkg;\n\n" else ""
        return buildString {
            append(pkgLine)
            append("import android.util.Log;\n\n")
            append("/**\n")
            append(" * Lightweight log utility generated by Logify.\n")
            append(" * Usage: L.d(this, \"message\");\n")
            append(" */\n")
            append("public class L {\n")
            append("    private L() {}\n\n")
            for ((method, level) in listOf("d" to "d", "e" to "e", "i" to "i", "w" to "w")) {
                append("    public static void $method(Object obj, String message) {\n")
                append("        Log.$level(obj.getClass().getSimpleName(), message);\n")
                append("    }\n\n")
            }
            append("}\n")
        }
    }
}
